### ISSUE TITLE
No data failure occurs too frequently.

### ISSUE THREAD

**Issue by micahjohnson150** [AdventureData/radicl#2]
* radicl version: 0.3.5
* Firmware version (if applicable): 1.45.2
* Python version: 3.6
* Operating System: linux

### Description

Trying to look at calibrated data.

### What I Did

```
radicl.probe DEBUG Stop Measurement Reqested.
radicl.probe INFO Waiting for state 3, current state = 1
radicl.probe ERROR getProbeMeasState error: COM
radicl.probe ERROR getProbeMeasState error: COM
radicl.probe ERROR getProbeMeasState error: COM
radicl.probe ERROR getProbeMeasState error: COM
radicl.probe ERROR getProbeMeasState error: COM
radicl.probe ERROR getProbeMeasState error: COM
radicl.probe ERROR getProbeMeasState error: COM
radicl.probe ERROR getProbeMeasState error: COM
radicl.probe ERROR getProbeMeasState error: COM
radicl.probe ERROR getProbeMeasState error: COM
radicl.probe DEBUG 5 queries while waiting for state 3
radicl.probe INFO Measurement stopped...
radicl.radicl INFO Downloading calibratedsensor data from probe...
radicl.radicl DEBUG Requesting data using function readCalibratedSensorData
radicl.probe INFO Waiting for state 3, current state = 3
radicl.probe DEBUG 1 queries while waiting for state 3
radicl.probe DEBUG Reading 1218 segments
Traceback (most recent call last):
  File "/home/micah/projects/venv/radiclenv/bin/radicl", line 11, in <module>
    load_entry_point('radicl', 'console_scripts', 'radicl')()
  File "/home/micah/projects/radicl/radicl/cli.py", line 64, in main
    cli.run()
  File "/home/micah/projects/radicl/radicl/radicl.py", line 99, in run
    self.tasking()
  File "/home/micah/projects/radicl/radicl/radicl.py", line 116, in tasking
    fn()
  File "/home/micah/projects/radicl/radicl/radicl.py", line 235, in task_daq
    self.data = self.take_a_reading(self.daq)
  File "/home/micah/projects/radicl/radicl/radicl.py", line 172, in take_a_reading
    data = self.grab_data(data_request)
  File "/home/micah/projects/radicl/radicl/radicl.py", line 204, in grab_data
    data = fn()
  File "/home/micah/projects/radicl/radicl/probe.py", line 437, in readCalibratedSensorData
    raw = self.readRawSensorData()
  File "/home/micah/projects/radicl/radicl/probe.py", line 386, in readRawSensorData
    ret = self.__readData(0)
  File "/home/micah/projects/radicl/radicl/probe.py", line 184, in __readData
    byte_counter = byte_counter + len(ret3['data'])
TypeError: object of type 'NoneType' has no len()

```

**Comment by micahjohnson150** [comment]
Not sure what fixed this but it is no longer an issue. Currently on Probe FW 1.45 and radicl 0.5.2
